In [5]:
import pandas as pd
import numpy as np

In [6]:
elastic=pd.read_csv("elastic_wardrive-01.kismet.csv",sep=";")

In [7]:
elastic.head()

,Network,NetType,ESSID,BSSID,Info,Channel,Cloaked,Encryption,Decrypted,MaxRate,...,GPSMaxLon,GPSMaxAlt,GPSMaxSpd,GPSBestLat,GPSBestLon,GPSBestAlt,DataSize,IPType,IP,Unnamed: 38
0,1,infrastructure,Ravitex,00:1E:42:13:43:87,NaN,13,No,"WPA2,AES-CCM",No,54.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0.0.0,NaN
1,2,infrastructure,TP-LINK_4E0DE3,C0:4A:00:4E:0D:E3,NaN,6,No,"OPN,None",No,135.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,10.254.254.121,NaN
2,3,infrastructure,Clicknet-A523,78:6A:89:09:A5:2C,NaN,1,No,"WPA2,AES-CCM",No,130.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0.0.0,NaN
3,4,infrastructure,E4ERNST,10:FE:ED:E6:AD:A2,NaN,1,No,"WPA2,AES-CCM,TKIP",No,130.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0.0.0,NaN
4,5,infrastructure,Cristi2.4,98:DE:D0:9F:06:96,NaN,4,No,"WPA2,AES-CCM",No,270.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0.0.0,NaN

In [8]:
elastic.shape

(2529, 39)

In [9]:
elastic.isnull().sum()

Network           0
NetType           0
ESSID            78
BSSID             0
Info           2529
Channel           0
Cloaked           0
Encryption        0
Decrypted         0
MaxRate           0
MaxSeenRate       0
Beacon            0
LLC               0
Data              0
Crypt             0
Weak              0
Total             0
Carrier        2529
Encoding       2529
FirstTime         0
LastTime          0
BestQuality       0
BestSignal        0
BestNoise         0
GPSMinLat         0
GPSMinLon         0
GPSMinAlt         0
GPSMinSpd         0
GPSMaxLat         0
GPSMaxLon         0
GPSMaxAlt         0
GPSMaxSpd         0
GPSBestLat        0
GPSBestLon        0
GPSBestAlt        0
DataSize          0
IPType            0
IP                0
Unnamed: 38    2529
dtype: int64

In [8]:
elastic.describe()

,Network,Info,Channel,MaxRate,MaxSeenRate,Beacon,LLC,Data,Crypt,Weak,...,GPSMaxLat,GPSMaxLon,GPSMaxAlt,GPSMaxSpd,GPSBestLat,GPSBestLon,GPSBestAlt,DataSize,IPType,Unnamed: 38
count,2529.000000,0.0,2529.000000,2529.000000,2529.0,2529.000000,2529.0,2529.000000,2529.0,2529.0,...,2529.0,2529.0,2529.0,2529.0,2529.0,2529.0,2529.0,2529.0,2529.0,0.0
mean,1265.000000,NaN,6.187426,154.506129,0.0,15.457098,0.0,1.440886,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
std,730.203739,NaN,3.859640,70.264741,0.0,28.222707,0.0,17.319405,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
min,1.000000,NaN,-1.000000,-1.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
25%,633.000000,NaN,2.000000,130.000000,0.0,3.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
50%,1265.000000,NaN,6.000000,130.000000,0.0,7.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
75%,1897.000000,NaN,10.000000,195.000000,0.0,16.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
max,2529.000000,NaN,13.000000,540.000000,0.0,491.000000,0.0,542.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN